-----------------------------------------
--Which contractors are working the most?
-----------------------------------------

SELECT CRID, TIMES_WORKED
FROM 
    (SELECT COUNT(CRID) AS TIMES_WORKED, CRID
     FROM TRANSACTION_HISTORY 
         GROUP BY CRID
         ORDER BY TIMES_WORKED DESC)
         
WHERE ROWNUM >= 1;

OR

SELECT FIRST_NAME, TIMES_WORKED
FROM 
    (SELECT COUNT(FIRST_NAME) AS TIMES_WORKED, FIRST_NAME
     FROM TRANSACTION_HISTORY INNER JOIN CONTRACTORS_INFO
         ON CONTRACTORS_INFO.CRID = TRANSACTION_HISTORY.CRID
         GROUP BY FIRST_NAME
         ORDER BY TIMES_WORKED DESC)
         
WHERE ROWNUM >= 1;

OR

CREATE VIEW CONTRACTORS
AS SELECT FIRST_NAME,LAST_NAME, TID
FROM CONTRACTORS_INFO ,TRANSACTION_HISTORY 
WHERE CONTRACTORS_INFO.CRID = TRANSACTION_HISTORY.CRID

SELECT *
FROM CONTRACTORS

*****FINAL*****

CREATE VIEW CONTRACTOR_TRANSACTIONS
AS SELECT FIRST_NAME, LAST_NAME, COUNT(TRANSACTION_HISTORY.CRID) TIMES_WORKED
FROM CONTRACTORS_INFO INNER JOIN TRANSACTION_HISTORY
ON CONTRACTORS_INFO.CRID = TRANSACTION_HISTORY.CRID
GROUP BY FIRST_NAME,LAST_NAME
HAVING COUNT(FIRST_NAME) >= 1
ORDER BY TIMES_WORKED DESC;
 
SELECT *
FROM CONTRACTOR_TRANSACTIONS



---------------------------------------
--Which customers use TripleS the most?
---------------------------------------

SELECT CID, TIMES_USED
FROM 
    (SELECT COUNT(CID) AS TIMES_USED, CID
     FROM TRANSACTION_HISTORY 
         GROUP BY CID
         ORDER BY TIMES_USED DESC)
         
WHERE ROWNUM >= 1;

OR

SELECT FIRST_NAME, TIMES_USED
FROM 
    (SELECT COUNT(FIRST_NAME) AS TIMES_USED, FIRST_NAME
     FROM TRANSACTION_HISTORY INNER JOIN CUSTOMER_INFO
         ON CUSTOMER_INFO.CID = TRANSACTION_HISTORY.CID
         GROUP BY FIRST_NAME
         ORDER BY TIMES_USED DESC)
         
WHERE ROWNUM >= 1;

OR

CREATE VIEW CUSTOMERS
AS SELECT FIRST_NAME,LAST_NAME, TID
FROM CUSTOMER_INFO ,TRANSACTION_HISTORY 
WHERE CUSTOMER_INFO.CID = TRANSACTION_HISTORY.CID

SELECT *
FROM CUSTOMERS


*****FINAL*****

CREATE VIEW CUSTOMER_TRANSACTIONS
AS SELECT FIRST_NAME, LAST_NAME, COUNT(TRANSACTION_HISTORY.CID) TIMES_USED
FROM CUSTOMER_INFO INNER JOIN TRANSACTION_HISTORY
ON CUSTOMER_INFO.CID = TRANSACTION_HISTORY.CID
GROUP BY FIRST_NAME,LAST_NAME
HAVING COUNT(FIRST_NAME) >= 1
ORDER BY TIMES_USED DESC;
 
SELECT *
FROM CUSTOMER_TRANSACTIONS



-------------------------------------
--Which services are needed the most?
-------------------------------------

SELECT SERVICE, AMOUNT_SERVED
FROM 
    (SELECT COUNT(SERVICE) AS AMOUNT_SERVED, SERVICE
     FROM TRANSACTION_HISTORY INNER JOIN SERVICES
         ON SERVICES.SID = TRANSACTION_HISTORY.SID
         GROUP BY SERVICE
         ORDER BY AMOUNT_SERVED DESC)
        
WHERE ROWNUM >= 1;


------------------------------------------
--Where are most of our customers located?
------------------------------------------

SELECT CITY, COUNT(CID) 
FROM CUSTOMER_LOCATION 
GROUP BY CITY
ORDER BY CITY DESC;
